// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v2/files/": {
            "get": {
                "description": "获取指定路径下的文件和目录列表，返回文件名、大小、权限、修改时间等信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "列出目录下的文件和子目录",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"hpc1\"",
                        "description": "集群名称",
                        "name": "cluster",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"/ai\"",
                        "description": "目录路径",
                        "name": "path",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "\"tsh_1234567890abcdef\"",
                        "description": "sessionKey",
                        "name": "request",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回文件列表",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "listContent": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/controller.FileInfoJSON"
                                    }
                                },
                                "listLength": {
                                    "type": "integer"
                                },
                                "success": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误或用户未登录",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "将指定路径的文件或目录重命名到新路径，支持文件和目录的重命名操作",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "重命名文件或目录",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"tsh_a2e932b625c0d598db3800aa91b92016\"",
                        "description": "SSH会话密钥",
                        "name": "sessionKey",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "重命名请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "new_path": {
                                    "type": "string"
                                },
                                "old_path": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "重命名成功\" example({\"success\":\"yes\"})",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "success": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "源文件或目录不存在",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "目标路径已存在",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误或用户未登录",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "在指定路径创建新的文件或目录，支持创建空文件和目录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "创建新文件或目录",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"tsh_a2e932b625c0d598db3800aa91b92016\"",
                        "description": "SSH会话密钥",
                        "name": "sessionKey",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "创建请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "path": {
                                    "type": "string"
                                },
                                "type": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功\" example({\"success\":\"yes\"})",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "success": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "文件或目录已存在",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误或用户未登录",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定路径的文件或目录，支持删除单个文件和空目录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "删除文件或目录",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"tsh_a2e932b625c0d598db3800aa91b92016\"",
                        "description": "SSH会话密钥",
                        "name": "sessionKey",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "删除请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "path": {
                                    "type": "string"
                                },
                                "type": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功\" example({\"success\":\"yes\"})",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "success": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "文件或目录不存在",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误或用户未登录",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v2/files/attr/": {
            "get": {
                "description": "获取指定路径文件或目录的详细属性信息，包括名称、大小、权限、修改时间等",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "获取文件或目录属性",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"tsh_a2e932b625c0d598db3800aa91b92016\"",
                        "description": "SSH会话密钥",
                        "name": "sessionKey",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"hpc1\"",
                        "description": "集群名称",
                        "name": "cluster",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"/ai/new_folder_rename/test_renamed.sh\"",
                        "description": "文件或目录路径",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取属性成功\" example({\"name\":\"test_renamed.sh\",\"size\":29,\"mode\":\"-rw-r--r--\",\"modify\":\"2025-08-07 10:16:36 +0800 CST\",\"isDir\":false})",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "isDir": {
                                    "type": "boolean"
                                },
                                "mode": {
                                    "type": "string"
                                },
                                "modify": {
                                    "type": "string"
                                },
                                "name": {
                                    "type": "string"
                                },
                                "size": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "文件或目录不存在",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误或用户未登录",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v2/files/chmod/": {
            "post": {
                "description": "修改指定路径文件或目录的权限模式，支持数字权限格式（如755、644等）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "修改文件或目录权限",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"tsh_a2e932b625c0d598db3800aa91b92016\"",
                        "description": "SSH会话密钥",
                        "name": "sessionKey",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "修改权限请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "mode": {
                                    "type": "string"
                                },
                                "path": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改权限成功\" example({\"success\":\"yes\"})",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "success": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误或权限格式无效",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "没有权限修改该文件",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "文件或目录不存在",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误或用户未登录",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v2/files/chown/": {
            "post": {
                "description": "修改指定路径文件或目录的所有者和组，需要提供用户ID和组ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "修改文件或目录所有者",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"tsh_a2e932b625c0d598db3800aa91b92016\"",
                        "description": "SSH会话密钥",
                        "name": "sessionKey",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "修改所有者请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "group": {
                                    "type": "string"
                                },
                                "owner": {
                                    "type": "string"
                                },
                                "path": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改所有者成功\" example({\"success\":\"yes\"})",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "success": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误或用户ID/组ID格式无效",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "没有权限修改该文件所有者",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "文件或目录不存在",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误或用户未登录",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v2/files/content/": {
            "get": {
                "description": "读取指定路径文件的内容，返回文件的文本内容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "读取文件内容",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"tsh_a2e932b625c0d598db3800aa91b92016\"",
                        "description": "SSH会话密钥",
                        "name": "sessionKey",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"hpc1\"",
                        "description": "集群名称",
                        "name": "cluster",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"/ai/new_folder_rename/test_renamed.sh\"",
                        "description": "文件路径",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "文件内容\" example(\"#!/bin/bash\\\\necho Hello World\")",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "文件不存在",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误或用户未登录",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "将指定内容写入到文件中，如果文件不存在会自动创建",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "写入文件内容",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"tsh_a2e932b625c0d598db3800aa91b92016\"",
                        "description": "SSH会话密钥",
                        "name": "sessionKey",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "写入内容请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "cluster": {
                                    "type": "string"
                                },
                                "content": {
                                    "type": "string"
                                },
                                "path": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "写入成功\" example({\"content\":\"\",\"success\":\"yes\"})",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "content": {
                                    "type": "string"
                                },
                                "success": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "文件路径不存在",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误或用户未登录",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v2/files/copy/": {
            "post": {
                "description": "将源路径的文件或目录复制到目标路径，支持文件和目录的复制操作",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "复制文件或目录",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"tsh_a2e932b625c0d598db3800aa91b92016\"",
                        "description": "SSH会话密钥",
                        "name": "sessionKey",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "复制请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "dst_path": {
                                    "type": "string"
                                },
                                "src_path": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "复制成功\" example({\"success\":\"yes\"})",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "success": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "源文件或目录不存在",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "目标路径已存在",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误或用户未登录",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v2/files/download/": {
            "get": {
                "description": "下载指定路径的文件或目录。文件直接下载，目录会被打包成ZIP文件下载",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "下载文件或目录",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"tsh_a2e932b625c0d598db3800aa91b92016\"",
                        "description": "SSH会话密钥",
                        "name": "sessionKey",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"hpc1\"",
                        "description": "集群名称",
                        "name": "cluster",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"/ai/mcp\"",
                        "description": "文件或目录路径",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "下载成功，返回文件内容或ZIP压缩包",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "文件或目录不存在",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误或用户未登录",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v2/files/execute/": {
            "post": {
                "description": "执行指定路径的脚本文件，使用bash解释器运行并返回执行结果",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "执行脚本文件",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"tsh_a2e932b625c0d598db3800aa91b92016\"",
                        "description": "SSH会话密钥",
                        "name": "sessionKey",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"hpc1\"",
                        "description": "集群名称",
                        "name": "cluster",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"/ai/new_folder_rename/test_renamed.sh\"",
                        "description": "脚本文件路径",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "执行成功，返回脚本输出\" example(\"Hello World\\nScript executed successfully\")",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "请求参数错误或路径是目录",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "脚本文件不存在",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误、用户未登录或脚本执行失败",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v2/files/move/": {
            "post": {
                "description": "将源路径的文件或目录移动到目标路径，支持文件和目录的移动操作",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "移动文件或目录",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"tsh_a2e932b625c0d598db3800aa91b92016\"",
                        "description": "SSH会话密钥",
                        "name": "sessionKey",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "移动请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "dst_path": {
                                    "type": "string"
                                },
                                "src_path": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "移动成功\" example({\"success\":\"yes\"})",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "success": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "源文件或目录不存在",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "目标路径已存在",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误或用户未登录",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v2/files/quota/": {
            "get": {
                "description": "获取指定用户或文件系统的磁盘配额信息，包括已使用空间、配额限制、文件数量等详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "获取磁盘配额信息",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"tsh_a2e932b625c0d598db3800aa91b92016\"",
                        "description": "SSH会话密钥",
                        "name": "sessionKey",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"hpc1\"",
                        "description": "集群名称",
                        "name": "cluster",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"/home/user\"",
                        "description": "查询路径",
                        "name": "path",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取配额信息成功\" example({\"filesystem\":\"/dev/sda1\",\"kbytes\":1024000,\"kbytes_quota\":2048000,\"kbytes_limit\":2097152,\"kbytes_grace\":\"none\",\"files\":1000,\"files_quota\":5000,\"files_limit\":10000,\"files_grace\":\"none\"})",
                        "schema": {
                            "$ref": "#/definitions/controller.QuotaInfo"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "路径不存在或配额信息不可用",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误或用户未登录",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v2/files/transmission/": {
            "post": {
                "description": "上传文件到指定路径，支持断点续传和文件覆盖更新功能",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "上传文件",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"tsh_a2e932b625c0d598db3800aa91b92016\"",
                        "description": "SSH会话密钥",
                        "name": "sessionKey",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"hpc1\"",
                        "description": "集群名称",
                        "name": "cluster",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"/ai/upload/test.txt\"",
                        "description": "上传路径",
                        "name": "path",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"0\"",
                        "description": "文件偏移量（用于断点续传）",
                        "name": "offset",
                        "in": "formData"
                    },
                    {
                        "enum": [
                            "true",
                            "false"
                        ],
                        "type": "string",
                        "example": "\"false\"",
                        "description": "是否覆盖已存在文件",
                        "name": "update",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "要上传的文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传成功\" example({\"success\":\"yes\"})",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "success": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误或文件为空",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "文件已存在且未设置覆盖标志",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误或用户未登录",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v2/login/": {
            "post": {
                "description": "创建SSH连接会话，验证用户凭据并返回会话密钥用于后续API调用",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证管理"
                ],
                "summary": "用户登录认证",
                "parameters": [
                    {
                        "description": "登录请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "cluster": {
                                    "type": "string"
                                },
                                "host": {
                                    "type": "string"
                                },
                                "password": {
                                    "type": "string"
                                },
                                "username": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功，返回用户主目录路径和会话密钥",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "home_path": {
                                    "type": "string"
                                },
                                "session_key": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "认证失败，用户名或密码错误",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误或SSH连接失败",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v2/logout/": {
            "get": {
                "description": "删除用户会话",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证管理"
                ],
                "summary": "用户登出",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话密钥",
                        "name": "session_key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登出成功",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误或用户未登录",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.FileInfoJSON": {
            "type": "object",
            "properties": {
                "isDir": {
                    "type": "boolean"
                },
                "mode": {
                    "type": "string"
                },
                "modify": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "controller.QuotaInfo": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "integer"
                },
                "files_grace": {
                    "type": "string"
                },
                "files_limit": {
                    "type": "integer"
                },
                "files_quota": {
                    "type": "integer"
                },
                "filesystem": {
                    "type": "string"
                },
                "kbytes": {
                    "type": "integer"
                },
                "kbytes_grace": {
                    "type": "string"
                },
                "kbytes_limit": {
                    "type": "integer"
                },
                "kbytes_quota": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
